DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
id SERIAL PRIMARY KEY,
 username VARCHAR(255) NOT NULL UNIQUE,
 passwords TEXT NOT NULL,
 email VARCHAR(255) NOT NULL UNIQUE,
 firstname VARCHAR(255) NOT NULL,
 lastname VARCHAR(255) NOT NULL
 )
 
 CREATE TABLE IF NOT EXISTS teams (
 id SERIAL PRIMARY KEY,
 team VARCHAR(255) NOT NULL,
  wins INTEGER NOT NULL DEFAULT 0,
  losses INTEGER NOT NULL DEFAULT 0,
 )
 
 CREATE TABLE IF NOT EXISTS players (
 id SERIAL PRIMARY KEY,
  firstname VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  ppg INTEGER,
  apg INTEGER,
  rpg INTEGER,
  team_id INTEGER,
  
  
 )